"""
Task - 11: Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a “cow”. 
For every digit the user guessed correctly in the wrong place is a “bull.” 
Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes throughout the game and 
tell the user at the end.

Say the number generated by the computer is 1038. 
An example interaction could look like this:
Welcome to the Cows and Bulls Game!
Enter a number:
>>> 1234
2 cows, 0 bulls
>>> 1356
1 cow, 1 bull
...
Until the user guesses the number.
"""

# import randint function to generate random number
from random import randint

# define a function to perform cows and bulls game
def cows_bulls_game(random_number):
    print("\nWelcome to the Cows and Bulls Game!\n")
    
    total_attempt = 0

    while True:    
        user_number = input("Enter a 4-digit number: ")

        cows = 0
        bulls = 0
        total_attempt += 1

        # check if user enters correct 4-digit number or not
        if len(user_number) == 4 and user_number.isdigit():
            
            remaining_user_number = []
            remaining_random_number = []

            # count cows
            for i in range(4):
                if user_number[i] == random_number[i]:
                    cows += 1
                else:
                    remaining_user_number.append(user_number[i])
                    remaining_random_number.append(random_number[i])

            # count bulls
            for j in remaining_user_number:
                if j in remaining_random_number:
                    bulls += 1
                    remaining_random_number.remove(j)
        
            # check if user_number is correctly matched or not
            if cows == 4:
                print(f"\nRandom number: {random_number}\nYour number: {user_number}")
                print(f"\nYour entered number is correct.\nTotal Attempts: {total_attempt}")
                break
            else:
                print(f"\nYour number: {user_number}\n{cows} cows, {bulls} bulls")
        else:
            print("\nPlease enter a valid 4-digit number.\n")

# generate a random number 
random_number = str(randint(1000, 9999))
# print(random_number)

# start the game
cows_bulls_game(random_number)